analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
  errors:
    avoid_final_parameters: ignore
    invalid_annotation_target: ignore
    use_setters_to_change_properties: ignore
  plugins:
    - custom_lint

include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false