analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false